#ifndef PROJECT_INCLUDE_CONSTANTS_H_
#define PROJECT_INCLUDE_CONSTANTS_H_

#define NULL_PTR_IN_ARGS (-1)
#define WRONG_SCANF (-2)
#define WRONG_COMPARATION (-3)
#define WRONG_PRINTF (-4)

#endif  // PROJECT_INCLUDE_CONSTANTS_H_
